import './js/categories';
import './js/toggle-switch';
import './js/mobile-menu';
import './js/best-sellers';
import './js/support-slider';
import './js/support-render-markup';
import './js/auth/auth-form-base';
import './js/pop-up';
import './js/scroll-up';
