import './js/categories';
import './js/toggle-switch';
import './js/mobile-menu';
import _ from './js/loader';
import './js/shopping-list';
import './js/best-sellers';
import './js/support-slider';
import './js/auth/auth-form-base';
import './js/pop-up';
import './js/scroll-up';
